//! `Invoice` aggregate — event-sourced via `es-entity` derive macros.
//!
//! `NewInvoice::try_new` is the validating constructor. It rejects
//! amount = 0 with `InvoiceError::InvalidAmount`, and silently coerces
//! out-of-range `expiry_seconds` to the BTC default (4 hours), matching
//! blink-core's behavior at `invoice-expiration.ts:33-37` so this gateway
//! reproduces the same semantics for callers being migrated over.
//! Returns a fully-formed `NewInvoice`.
//!
//! The repo (`Invoices`, generated by `#[derive(EsRepo)]`) then calls
//! `NewInvoice::into_events` during `create_in_op` — that call cannot
//! fail (the trait method returns `EntityEvents<InvoiceEvent>`, not a
//! `Result`), which is why all validation has to happen earlier in
//! `try_new`. From there `create_in_op` persists the projection row +
//! event row in one tx and hydrates the entity via `TryFromEvents`.
//!
//! Story 2.3 adds the `Pending → Held / Settled / Canceled` state
//! machine. `Invoice::mark_held / settle / cancel` use the same
//! `idempotency_guard!` shape Payment adopted in Story 2.2.

use es_entity::{
    idempotency_guard, EntityEvents, EsEntity, EsEntityError, Idempotent, IntoEvents, TryFromEvents,
};
use serde::{Deserialize, Serialize};
use std::fmt;

use super::{
    error::InvoiceError,
    event::{CancelReason, InvoiceEvent},
};
use crate::primitives::{
    BoltInvoice, InvoiceId, MilliSatoshi, PaymentHash, Preimage, Timestamp, WalletId,
};

const SECS_PER_MIN: u32 = 60;
const SECS_PER_HOUR: u32 = 60 * 60;
const SECS_PER_4_HOURS: u32 = SECS_PER_HOUR * 4;
const SECS_PER_DAY: u32 = SECS_PER_HOUR * 24;

// BTC invoice expiration policy
//
// Out-of-range expiry values are silently coerced to
// `BTC_INVOICE_DEFAULT_SECONDS`, matching blink-core's behavior
const BTC_INVOICE_MIN_SECONDS: u32 = SECS_PER_MIN;
const BTC_INVOICE_MAX_SECONDS: u32 = SECS_PER_DAY;
const BTC_INVOICE_DEFAULT_SECONDS: u32 = SECS_PER_4_HOURS;

/// Lifecycle state. Slice 1a created invoices in `Pending`; Story 2.3
/// adds the three observed terminal-ish states (`Held` is held-but-not-
/// terminal, `Settled` and `Canceled` are terminal).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "TEXT", rename_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum InvoiceState {
    Pending,
    Held,
    Settled,
    Canceled,
}

impl InvoiceState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Held => "held",
            Self::Settled => "settled",
            Self::Canceled => "canceled",
        }
    }
}

impl fmt::Display for InvoiceState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Validated input for creating an invoice. Built via `NewInvoice::try_new`,
/// which rejects zero-amount and coerces out-of-range expiry to the BTC
/// default. Values that reach this struct are guaranteed to satisfy the
/// entity invariants, so `IntoEvents::into_events` does not need to
/// return a `Result` — every `NewInvoice` already represents valid input
/// by the time it gets here.
///
/// `id` is generated by `try_new` and stored here so the repo's
/// `create_in_op` can use it for both the projection-row insert and the
/// `EntityEvents::init(id, ...)` grouping.
#[derive(Clone, Debug)]
pub struct NewInvoice {
    pub id: InvoiceId,
    pub payment_hash: PaymentHash,
    pub wallet_id: WalletId,
    pub amount_msat: MilliSatoshi,
    pub expiry_at: Timestamp,
    pub bolt_invoice: BoltInvoice,
    pub created_at: Timestamp,
}

impl NewInvoice {
    /// Validating constructor. Returns `Err(InvoiceError::InvalidAmount)`
    /// if amount is zero. Out-of-range `expiry_seconds` (outside
    /// `[BTC_INVOICE_MIN_SECONDS, BTC_INVOICE_MAX_SECONDS]` = 60s..=24h)
    /// is silently coerced to `BTC_INVOICE_DEFAULT_SECONDS` (4 hours)
    ///
    /// `memo` is *not* a parameter here — the App passes it to LND as
    /// part of `AddInvoiceParams` so it ends up encoded inside the
    /// returned `bolt_invoice` (BOLT11's `d` field), but we don't store
    /// it as a separate column or event field. Same shape as blink-core.
    pub fn try_new(
        payment_hash: PaymentHash,
        wallet_id: WalletId,
        amount_msat: MilliSatoshi,
        expiry_seconds: u32,
        bolt_invoice: BoltInvoice,
        now: Timestamp,
    ) -> Result<Self, InvoiceError> {
        if amount_msat.as_u64() == 0 {
            return Err(InvoiceError::InvalidAmount);
        }
        let effective_expiry =
            if (BTC_INVOICE_MIN_SECONDS..=BTC_INVOICE_MAX_SECONDS).contains(&expiry_seconds) {
                expiry_seconds
            } else {
                BTC_INVOICE_DEFAULT_SECONDS
            };
        let expiry_at = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(effective_expiry)),
        );
        Ok(Self {
            id: InvoiceId::new(),
            payment_hash,
            wallet_id,
            amount_msat,
            expiry_at,
            bolt_invoice,
            created_at: now,
        })
    }

    /// Accessor read by `EsRepo`'s `create(accessor = "state_str()")`. New
    /// invoices land in `Pending`.
    pub fn state_str(&self) -> String {
        InvoiceState::Pending.as_str().to_owned()
    }
}

impl IntoEvents<InvoiceEvent> for NewInvoice {
    fn into_events(self) -> EntityEvents<InvoiceEvent> {
        EntityEvents::init(
            self.id,
            [InvoiceEvent::Created {
                payment_hash: self.payment_hash,
                wallet_id: self.wallet_id,
                amount_msat: self.amount_msat,
                expiry_at: self.expiry_at,
                bolt_invoice: self.bolt_invoice,
                created_at: self.created_at,
            }],
        )
    }
}

/// Hydrated invoice aggregate. Constructed from the event log via
/// `TryFromEvents`; never built directly outside this module.
#[derive(EsEntity)]
pub struct Invoice {
    pub id: InvoiceId,
    pub payment_hash: PaymentHash,
    pub wallet_id: WalletId,
    pub amount_msat: MilliSatoshi,
    pub expiry_at: Timestamp,
    pub state: InvoiceState,
    pub created_at: Timestamp,
    pub payment_preimage: Option<Preimage>,
    pub canceled_reason: Option<CancelReason>,
    events: EntityEvents<InvoiceEvent>,
}

impl Invoice {
    /// Accessor read by `EsRepo`'s `update(accessor = "state_str()")`.
    pub fn state_str(&self) -> String {
        self.state.as_str().to_owned()
    }

    /// Transition `Pending → Held` on LND `Accepted` (HTLC parked on a
    /// HOLD invoice). Idempotent on a prior `HtlcHeld` event when the
    /// projected state is already `Held` (duplicate per-hash listener
    /// replay).
    pub fn mark_held(
        &mut self,
        htlc_amount_msat: MilliSatoshi,
        held_at: Timestamp,
    ) -> Result<Idempotent<()>, InvoiceError> {
        idempotency_guard!(self.events.iter_all().rev(), InvoiceEvent::HtlcHeld { .. });
        if !matches!(self.state, InvoiceState::Pending) {
            return Err(InvoiceError::InvalidStateTransition {
                from: self.state,
                attempted: "mark_held",
            });
        }
        self.events.push(InvoiceEvent::HtlcHeld {
            held_at,
            htlc_amount_msat,
        });
        self.state = InvoiceState::Held;
        Ok(Idempotent::Executed(()))
    }

    /// Transition `(Pending|Held) → Settled` on LND `Settled` /
    /// `is_confirmed`. Story 2.3 only drives `Pending → Settled` via
    /// `App::handle_invoice_update`; Story 2.4 drives `Held → Settled`
    /// via the explicit settle-hold-invoice command. Accepting both
    /// source states now avoids a future entity-API revision when 2.4
    /// lands.
    ///
    /// Idempotent on any prior `Settled` event (duplicate replay). A
    /// prior `Canceled` is a genuine contradiction and surfaces as
    /// `InvalidStateTransition`.
    pub fn settle(
        &mut self,
        payment_preimage: Preimage,
        settled_at: Timestamp,
    ) -> Result<Idempotent<()>, InvoiceError> {
        idempotency_guard!(self.events.iter_all().rev(), InvoiceEvent::Settled { .. });
        if !matches!(self.state, InvoiceState::Pending | InvoiceState::Held) {
            return Err(InvoiceError::InvalidStateTransition {
                from: self.state,
                attempted: "settle",
            });
        }
        self.events.push(InvoiceEvent::Settled {
            settled_at,
            payment_preimage,
        });
        self.state = InvoiceState::Settled;
        self.payment_preimage = Some(payment_preimage);
        Ok(Idempotent::Executed(()))
    }

    /// Transition `(Pending|Held) → Canceled`. Idempotent on a prior
    /// `Canceled` event. `Settled` is a genuine contradiction.
    pub fn cancel(
        &mut self,
        reason: CancelReason,
        canceled_at: Timestamp,
    ) -> Result<Idempotent<()>, InvoiceError> {
        idempotency_guard!(self.events.iter_all().rev(), InvoiceEvent::Canceled { .. });
        if !matches!(self.state, InvoiceState::Pending | InvoiceState::Held) {
            return Err(InvoiceError::InvalidStateTransition {
                from: self.state,
                attempted: "cancel",
            });
        }
        self.events.push(InvoiceEvent::Canceled {
            canceled_at,
            reason: reason.clone(),
        });
        self.state = InvoiceState::Canceled;
        self.canceled_reason = Some(reason);
        Ok(Idempotent::Executed(()))
    }
}

// `EntityEvents` does not derive `Debug` in es-entity 0.9.5, so we cannot
// auto-derive `Debug` on `Invoice`. Hand-impl excludes the events field;
// callers that need event-level inspection use `Invoice::events()` /
// `Invoice::events_mut()` from the `EsEntity` impl.
impl fmt::Debug for Invoice {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Invoice")
            .field("id", &self.id)
            .field("payment_hash", &self.payment_hash)
            .field("wallet_id", &self.wallet_id)
            .field("amount_msat", &self.amount_msat)
            .field("expiry_at", &self.expiry_at)
            .field("state", &self.state)
            .field("created_at", &self.created_at)
            .field("payment_preimage", &self.payment_preimage)
            .field("canceled_reason", &self.canceled_reason)
            .finish()
    }
}

impl TryFromEvents<InvoiceEvent> for Invoice {
    fn try_from_events(events: EntityEvents<InvoiceEvent>) -> Result<Self, EsEntityError> {
        let id = *events.id();
        let mut iter = events.iter_all();
        let first = iter.next().ok_or(EsEntityError::NotFound)?;
        let InvoiceEvent::Created {
            payment_hash,
            wallet_id,
            amount_msat,
            expiry_at,
            created_at,
            ..
        } = first
        else {
            ::tracing::error!(
                invoice_id = %id,
                "invoice event log does not start with Created — CORRUPT LOG; surfacing as NotFound"
            );
            return Err(EsEntityError::NotFound);
        };

        let mut state = InvoiceState::Pending;
        let mut payment_preimage: Option<Preimage> = None;
        let mut canceled_reason: Option<CancelReason> = None;

        for ev in iter {
            match ev {
                InvoiceEvent::Created { .. } => {
                    ::tracing::error!(
                        invoice_id = %id,
                        "invoice event log contains duplicate Created — CORRUPT LOG; surfacing as NotFound"
                    );
                    return Err(EsEntityError::NotFound);
                }
                InvoiceEvent::HtlcHeld { .. } => state = InvoiceState::Held,
                InvoiceEvent::Settled {
                    payment_preimage: p,
                    ..
                } => {
                    state = InvoiceState::Settled;
                    payment_preimage = Some(*p);
                }
                InvoiceEvent::Canceled { reason, .. } => {
                    state = InvoiceState::Canceled;
                    canceled_reason = Some(reason.clone());
                }
            }
        }

        Ok(Invoice {
            id,
            payment_hash: *payment_hash,
            wallet_id: *wallet_id,
            amount_msat: *amount_msat,
            expiry_at: *expiry_at,
            state,
            created_at: *created_at,
            payment_preimage,
            canceled_reason,
            events,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{TimeZone, Utc};
    use uuid::Uuid;

    fn fixed_now() -> Timestamp {
        Timestamp::from(Utc.with_ymd_and_hms(2026, 5, 7, 10, 0, 0).unwrap())
    }

    fn ok_args() -> (PaymentHash, WalletId, MilliSatoshi, u32, BoltInvoice) {
        (
            PaymentHash::from([0xaa; 32]),
            WalletId::from(Uuid::now_v7()),
            MilliSatoshi::new(1_000_000),
            3600,
            BoltInvoice::new("lnbc1u1pj..."),
        )
    }

    #[test]
    fn try_new_happy_path_constructs_new_invoice() {
        let (h, w, a, e, b) = ok_args();
        let now = fixed_now();
        let new = NewInvoice::try_new(h, w, a, e, b, now).expect("happy path");
        assert_eq!(new.amount_msat, MilliSatoshi::new(1_000_000));
        assert_eq!(new.created_at, now);
        let expected_expiry = Timestamp::from(now.into_inner() + chrono::Duration::seconds(3600));
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_coerces_expiry_below_min_to_default() {
        let (h, w, a, _, b) = ok_args();
        let now = fixed_now();
        let low_expiry = BTC_INVOICE_MIN_SECONDS - 1;
        let new = NewInvoice::try_new(h, w, a, low_expiry, b, now).expect("coerced, not rejected");
        let expected_expiry = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(BTC_INVOICE_DEFAULT_SECONDS)),
        );
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_coerces_expiry_above_max_to_default() {
        let (h, w, a, _, b) = ok_args();
        let now = fixed_now();
        let high_expiry = BTC_INVOICE_MAX_SECONDS + 1;
        let new = NewInvoice::try_new(h, w, a, high_expiry, b, now).expect("coerced, not rejected");
        let expected_expiry = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(BTC_INVOICE_DEFAULT_SECONDS)),
        );
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_rejects_zero_amount() {
        let (h, w, _, e, b) = ok_args();
        let err = NewInvoice::try_new(h, w, MilliSatoshi::ZERO, e, b, fixed_now()).unwrap_err();
        assert!(matches!(err, InvoiceError::InvalidAmount));
    }

    #[test]
    fn try_new_accepts_minimum_expiry() {
        let (h, w, a, _, b) = ok_args();
        assert!(NewInvoice::try_new(h, w, a, BTC_INVOICE_MIN_SECONDS, b, fixed_now()).is_ok());
    }

    #[test]
    fn try_new_accepts_maximum_expiry() {
        let (h, w, a, _, b) = ok_args();
        assert!(NewInvoice::try_new(h, w, a, BTC_INVOICE_MAX_SECONDS, b, fixed_now()).is_ok());
    }

    #[test]
    fn try_from_events_reconstructs_pending_invoice() {
        let (h, w, a, e, b) = ok_args();
        let now = fixed_now();
        let new = NewInvoice::try_new(h, w, a, e, b, now).unwrap();
        let id = new.id;
        let entity_events = new.into_events();
        let invoice = Invoice::try_from_events(entity_events).expect("hydrate");
        assert_eq!(invoice.id, id);
        assert_eq!(invoice.state, InvoiceState::Pending);
        assert_eq!(invoice.amount_msat, MilliSatoshi::new(1_000_000));
        assert_eq!(invoice.created_at, now);
        assert!(invoice.payment_preimage.is_none());
        assert!(invoice.canceled_reason.is_none());
    }

    #[test]
    fn try_from_events_with_no_events_returns_not_found() {
        let id = InvoiceId::new();
        let empty: EntityEvents<InvoiceEvent> = EntityEvents::init(id, std::iter::empty());
        let err = Invoice::try_from_events(empty).unwrap_err();
        assert!(matches!(err, EsEntityError::NotFound));
    }

    // ---- Story 2.3: command-method state machine ----------------------

    fn fresh_invoice() -> Invoice {
        let (h, w, a, e, b) = ok_args();
        let new = NewInvoice::try_new(h, w, a, e, b, fixed_now()).unwrap();
        Invoice::try_from_events(new.into_events()).unwrap()
    }

    /// Fast-forward to an arbitrary state without going through command
    /// methods — lets a single test start from any state.
    fn push_event(inv: &mut Invoice, event: InvoiceEvent, new_state: InvoiceState) {
        inv.events_mut().extend(std::iter::once(event));
        inv.state = new_state;
    }

    fn sample_held_event() -> InvoiceEvent {
        InvoiceEvent::HtlcHeld {
            held_at: fixed_now(),
            htlc_amount_msat: MilliSatoshi::new(1_000_000),
        }
    }

    fn sample_settled_event() -> InvoiceEvent {
        InvoiceEvent::Settled {
            settled_at: fixed_now(),
            payment_preimage: Preimage::from([0xee; 32]),
        }
    }

    fn sample_canceled_event() -> InvoiceEvent {
        InvoiceEvent::Canceled {
            canceled_at: fixed_now(),
            reason: CancelReason::Expired,
        }
    }

    #[test]
    fn mark_held_from_pending_executes() {
        let mut inv = fresh_invoice();
        let outcome = inv
            .mark_held(MilliSatoshi::new(1_000_000), fixed_now())
            .unwrap();
        assert!(matches!(outcome, Idempotent::Executed(())));
        assert_eq!(inv.state, InvoiceState::Held);
    }

    #[test]
    fn settle_from_pending_executes() {
        let mut inv = fresh_invoice();
        let preimage = Preimage::from([0xee; 32]);
        let outcome = inv.settle(preimage, fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Executed(())));
        assert_eq!(inv.state, InvoiceState::Settled);
        assert_eq!(inv.payment_preimage, Some(preimage));
    }

    #[test]
    fn settle_from_held_executes() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_held_event(), InvoiceState::Held);
        let preimage = Preimage::from([0xee; 32]);
        let outcome = inv.settle(preimage, fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Executed(())));
        assert_eq!(inv.state, InvoiceState::Settled);
    }

    #[test]
    fn cancel_from_pending_executes() {
        let mut inv = fresh_invoice();
        let outcome = inv.cancel(CancelReason::Expired, fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Executed(())));
        assert_eq!(inv.state, InvoiceState::Canceled);
        assert_eq!(inv.canceled_reason, Some(CancelReason::Expired));
    }

    #[test]
    fn cancel_from_held_executes() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_held_event(), InvoiceState::Held);
        let outcome = inv.cancel(CancelReason::Manual, fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Executed(())));
        assert_eq!(inv.state, InvoiceState::Canceled);
    }

    // ---- idempotent replays --------------------------------------------

    #[test]
    fn mark_held_from_held_is_idempotent() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_held_event(), InvoiceState::Held);
        let outcome = inv
            .mark_held(MilliSatoshi::new(1_000_000), fixed_now())
            .unwrap();
        assert!(matches!(outcome, Idempotent::Ignored));
    }

    #[test]
    fn settle_from_settled_is_idempotent() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_settled_event(), InvoiceState::Settled);
        let outcome = inv.settle(Preimage::from([0xee; 32]), fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Ignored));
    }

    #[test]
    fn cancel_from_canceled_is_idempotent() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_canceled_event(), InvoiceState::Canceled);
        let outcome = inv.cancel(CancelReason::Expired, fixed_now()).unwrap();
        assert!(matches!(outcome, Idempotent::Ignored));
    }

    // ---- genuine contradictions -----------------------------------------

    #[test]
    fn mark_held_from_settled_is_invalid_state_transition() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_settled_event(), InvoiceState::Settled);
        match inv.mark_held(MilliSatoshi::new(1), fixed_now()) {
            Err(InvoiceError::InvalidStateTransition {
                attempted: "mark_held",
                ..
            }) => {}
            Err(other) => panic!("expected InvalidStateTransition(mark_held), got {other:?}"),
            Ok(_) => panic!("expected InvalidStateTransition(mark_held), got Ok"),
        }
    }

    #[test]
    fn settle_from_canceled_is_invalid_state_transition() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_canceled_event(), InvoiceState::Canceled);
        match inv.settle(Preimage::from([0xee; 32]), fixed_now()) {
            Err(InvoiceError::InvalidStateTransition {
                attempted: "settle",
                ..
            }) => {}
            Err(other) => panic!("expected InvalidStateTransition(settle), got {other:?}"),
            Ok(_) => panic!("expected InvalidStateTransition(settle), got Ok"),
        }
    }

    #[test]
    fn cancel_from_settled_is_invalid_state_transition() {
        let mut inv = fresh_invoice();
        push_event(&mut inv, sample_settled_event(), InvoiceState::Settled);
        match inv.cancel(CancelReason::Expired, fixed_now()) {
            Err(InvoiceError::InvalidStateTransition {
                attempted: "cancel",
                ..
            }) => {}
            Err(other) => panic!("expected InvalidStateTransition(cancel), got {other:?}"),
            Ok(_) => panic!("expected InvalidStateTransition(cancel), got Ok"),
        }
    }

    // ---- TryFromEvents fold --------------------------------------------

    #[test]
    fn try_from_events_reconstructs_settled_after_held_invoice() {
        // Created → HtlcHeld → Settled. Confirms the fold walks the new
        // variants and that the final state plus preimage projection are
        // recovered from the log.
        let (h, w, a, e, b) = ok_args();
        let new = NewInvoice::try_new(h, w, a, e, b, fixed_now()).unwrap();
        let id = new.id;
        let preimage = Preimage::from([0xee; 32]);
        let events = EntityEvents::init(
            id,
            [
                InvoiceEvent::Created {
                    payment_hash: h,
                    wallet_id: w,
                    amount_msat: a,
                    expiry_at: Timestamp::from(
                        fixed_now().into_inner() + chrono::Duration::seconds(i64::from(e)),
                    ),
                    bolt_invoice: BoltInvoice::new("lnbc1u1pj..."),
                    created_at: fixed_now(),
                },
                InvoiceEvent::HtlcHeld {
                    held_at: fixed_now(),
                    htlc_amount_msat: a,
                },
                InvoiceEvent::Settled {
                    settled_at: fixed_now(),
                    payment_preimage: preimage,
                },
            ],
        );
        let invoice = Invoice::try_from_events(events).unwrap();
        assert_eq!(invoice.state, InvoiceState::Settled);
        assert_eq!(invoice.payment_preimage, Some(preimage));
        // Use new.id consumed by referencing it earlier — assertion via the
        // hydrated invoice keeps the test self-contained.
        let _ = new;
    }

    #[test]
    fn try_from_events_reconstructs_canceled_invoice() {
        let (h, w, a, e, b) = ok_args();
        let new = NewInvoice::try_new(h, w, a, e, b, fixed_now()).unwrap();
        let id = new.id;
        let events = EntityEvents::init(
            id,
            [
                InvoiceEvent::Created {
                    payment_hash: h,
                    wallet_id: w,
                    amount_msat: a,
                    expiry_at: Timestamp::from(
                        fixed_now().into_inner() + chrono::Duration::seconds(i64::from(e)),
                    ),
                    bolt_invoice: BoltInvoice::new("lnbc1u1pj..."),
                    created_at: fixed_now(),
                },
                InvoiceEvent::Canceled {
                    canceled_at: fixed_now(),
                    reason: CancelReason::Expired,
                },
            ],
        );
        let invoice = Invoice::try_from_events(events).unwrap();
        assert_eq!(invoice.state, InvoiceState::Canceled);
        assert_eq!(invoice.canceled_reason, Some(CancelReason::Expired));
    }
}
