//! `Invoice` aggregate — event-sourced via `es-entity` derive macros.
//!
//! `NewInvoice::try_new` is the validating constructor. It rejects
//! amount = 0 with `InvoiceError::InvalidAmount`, and silently coerces
//! out-of-range `expiry_seconds` to the BTC default (4 hours), matching
//! blink-core's behavior at `invoice-expiration.ts:33-37` so this gateway
//! reproduces the same semantics for callers being migrated over.
//! Returns a fully-formed `NewInvoice`.
//!
//! The repo (`Invoices`, generated by `#[derive(EsRepo)]`) then calls
//! `NewInvoice::into_events` during `create_in_op` — that call cannot
//! fail (the trait method returns `EntityEvents<InvoiceEvent>`, not a
//! `Result`), which is why all validation has to happen earlier in
//! `try_new`. From there `create_in_op` persists the projection row +
//! event row in one tx and hydrates the entity via `TryFromEvents`.

use es_entity::{EntityEvents, EsEntity, EsEntityError, IntoEvents, TryFromEvents};
use serde::{Deserialize, Serialize};
use std::fmt;

use super::{error::InvoiceError, event::InvoiceEvent};
use crate::primitives::{BoltInvoice, InvoiceId, MilliSatoshi, PaymentHash, Timestamp, WalletId};

const SECS_PER_MIN: u32 = 60;
const SECS_PER_HOUR: u32 = 60 * 60;
const SECS_PER_4_HOURS: u32 = SECS_PER_HOUR * 4;
const SECS_PER_DAY: u32 = SECS_PER_HOUR * 24;

// BTC invoice expiration policy
//
// Out-of-range expiry values are silently coerced to
// `BTC_INVOICE_DEFAULT_SECONDS`, matching blink-core's behavior
const BTC_INVOICE_MIN_SECONDS: u32 = SECS_PER_MIN;
const BTC_INVOICE_MAX_SECONDS: u32 = SECS_PER_DAY;
const BTC_INVOICE_DEFAULT_SECONDS: u32 = SECS_PER_4_HOURS;

/// Lifecycle state. Slice 1a only ever creates invoices in `Pending`;
/// `Settled` / `Cancelled` arrive with Story 2.2 (HOLD lifecycle).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "TEXT", rename_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum InvoiceState {
    Pending,
}

impl InvoiceState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
        }
    }
}

impl fmt::Display for InvoiceState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Validated input for creating an invoice. Built via `NewInvoice::try_new`,
/// which rejects zero-amount and coerces out-of-range expiry to the BTC
/// default. Values that reach this struct are guaranteed to satisfy the
/// entity invariants, so `IntoEvents::into_events` does not need to
/// return a `Result` — every `NewInvoice` already represents valid input
/// by the time it gets here.
///
/// `id` is generated by `try_new` and stored here so the repo's
/// `create_in_op` can use it for both the projection-row insert and the
/// `EntityEvents::init(id, ...)` grouping.
#[derive(Clone, Debug)]
pub struct NewInvoice {
    pub id: InvoiceId,
    pub payment_hash: PaymentHash,
    pub wallet_id: WalletId,
    pub amount_msat: MilliSatoshi,
    pub expiry_at: Timestamp,
    pub bolt_invoice: BoltInvoice,
    pub created_at: Timestamp,
}

impl NewInvoice {
    /// Validating constructor. Returns `Err(InvoiceError::InvalidAmount)`
    /// if amount is zero. Out-of-range `expiry_seconds` (outside
    /// `[BTC_INVOICE_MIN_SECONDS, BTC_INVOICE_MAX_SECONDS]` = 60s..=24h)
    /// is silently coerced to `BTC_INVOICE_DEFAULT_SECONDS` (4 hours)
    ///
    /// `memo` is *not* a parameter here — the App passes it to LND as
    /// part of `AddInvoiceParams` so it ends up encoded inside the
    /// returned `bolt_invoice` (BOLT11's `d` field), but we don't store
    /// it as a separate column or event field. Same shape as blink-core.
    pub fn try_new(
        payment_hash: PaymentHash,
        wallet_id: WalletId,
        amount_msat: MilliSatoshi,
        expiry_seconds: u32,
        bolt_invoice: BoltInvoice,
        now: Timestamp,
    ) -> Result<Self, InvoiceError> {
        if amount_msat.as_u64() == 0 {
            return Err(InvoiceError::InvalidAmount);
        }
        let effective_expiry =
            if (BTC_INVOICE_MIN_SECONDS..=BTC_INVOICE_MAX_SECONDS).contains(&expiry_seconds) {
                expiry_seconds
            } else {
                BTC_INVOICE_DEFAULT_SECONDS
            };
        let expiry_at = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(effective_expiry)),
        );
        Ok(Self {
            id: InvoiceId::new(),
            payment_hash,
            wallet_id,
            amount_msat,
            expiry_at,
            bolt_invoice,
            created_at: now,
        })
    }

    /// Accessor read by `EsRepo`'s `create(accessor = "state_str()")`. New
    /// invoices land in `Pending`.
    pub fn state_str(&self) -> String {
        InvoiceState::Pending.as_str().to_owned()
    }
}

impl IntoEvents<InvoiceEvent> for NewInvoice {
    fn into_events(self) -> EntityEvents<InvoiceEvent> {
        EntityEvents::init(
            self.id,
            [InvoiceEvent::Created {
                payment_hash: self.payment_hash,
                wallet_id: self.wallet_id,
                amount_msat: self.amount_msat,
                expiry_at: self.expiry_at,
                bolt_invoice: self.bolt_invoice,
                created_at: self.created_at,
            }],
        )
    }
}

/// Hydrated invoice aggregate. Constructed from the event log via
/// `TryFromEvents`; never built directly outside this module.
#[derive(EsEntity)]
pub struct Invoice {
    pub id: InvoiceId,
    pub payment_hash: PaymentHash,
    pub wallet_id: WalletId,
    pub amount_msat: MilliSatoshi,
    pub expiry_at: Timestamp,
    pub state: InvoiceState,
    pub created_at: Timestamp,
    events: EntityEvents<InvoiceEvent>,
}

impl Invoice {
    /// Accessor read by `EsRepo`'s `update(accessor = "state_str()")`.
    pub fn state_str(&self) -> String {
        self.state.as_str().to_owned()
    }
}

// `EntityEvents` does not derive `Debug` in es-entity 0.9.5, so we cannot
// auto-derive `Debug` on `Invoice`. Hand-impl excludes the events field;
// callers that need event-level inspection use `Invoice::events()` /
// `Invoice::events_mut()` from the `EsEntity` impl.
impl fmt::Debug for Invoice {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Invoice")
            .field("id", &self.id)
            .field("payment_hash", &self.payment_hash)
            .field("wallet_id", &self.wallet_id)
            .field("amount_msat", &self.amount_msat)
            .field("expiry_at", &self.expiry_at)
            .field("state", &self.state)
            .field("created_at", &self.created_at)
            .finish()
    }
}

impl TryFromEvents<InvoiceEvent> for Invoice {
    fn try_from_events(events: EntityEvents<InvoiceEvent>) -> Result<Self, EsEntityError> {
        // Slice 1a: the only event variant is `Created`, which carries every
        // initialization field. With one variant, destructuring the first
        // event proves all fields are populated; no Option<T> accumulator is
        // needed. When Story 2.2 adds Settled / Cancelled variants we'll
        // extend the iteration to update `state` after the initial seed.
        let id = *events.id();
        let mut iter = events.iter_all();
        let first = iter.next().ok_or(EsEntityError::NotFound)?;
        let InvoiceEvent::Created {
            payment_hash,
            wallet_id,
            amount_msat,
            expiry_at,
            created_at,
            ..
        } = first;

        let state = InvoiceState::Pending;
        // Drain remaining events here when Story 2.2 introduces lifecycle
        // transitions. For now there are none.
        for _ev in iter {}

        Ok(Invoice {
            id,
            payment_hash: *payment_hash,
            wallet_id: *wallet_id,
            amount_msat: *amount_msat,
            expiry_at: *expiry_at,
            state,
            created_at: *created_at,
            events,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{TimeZone, Utc};
    use uuid::Uuid;

    fn fixed_now() -> Timestamp {
        Timestamp::from(Utc.with_ymd_and_hms(2026, 5, 7, 10, 0, 0).unwrap())
    }

    fn ok_args() -> (PaymentHash, WalletId, MilliSatoshi, u32, BoltInvoice) {
        (
            PaymentHash::from([0xaa; 32]),
            WalletId::from(Uuid::now_v7()),
            MilliSatoshi::new(1_000_000),
            3600,
            BoltInvoice::new("lnbc1u1pj..."),
        )
    }

    #[test]
    fn try_new_happy_path_constructs_new_invoice() {
        let (h, w, a, e, b) = ok_args();
        let now = fixed_now();
        let new = NewInvoice::try_new(h, w, a, e, b, now).expect("happy path");
        assert_eq!(new.amount_msat, MilliSatoshi::new(1_000_000));
        assert_eq!(new.created_at, now);
        let expected_expiry = Timestamp::from(now.into_inner() + chrono::Duration::seconds(3600));
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_coerces_expiry_below_min_to_default() {
        let (h, w, a, _, b) = ok_args();
        let now = fixed_now();
        let low_expiry = BTC_INVOICE_MIN_SECONDS - 1;
        let new = NewInvoice::try_new(h, w, a, low_expiry, b, now).expect("coerced, not rejected");
        let expected_expiry = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(BTC_INVOICE_DEFAULT_SECONDS)),
        );
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_coerces_expiry_above_max_to_default() {
        let (h, w, a, _, b) = ok_args();
        let now = fixed_now();
        let high_expiry = BTC_INVOICE_MAX_SECONDS + 1;
        let new = NewInvoice::try_new(h, w, a, high_expiry, b, now).expect("coerced, not rejected");
        let expected_expiry = Timestamp::from(
            now.into_inner() + chrono::Duration::seconds(i64::from(BTC_INVOICE_DEFAULT_SECONDS)),
        );
        assert_eq!(new.expiry_at, expected_expiry);
    }

    #[test]
    fn try_new_rejects_zero_amount() {
        let (h, w, _, e, b) = ok_args();
        let err = NewInvoice::try_new(h, w, MilliSatoshi::ZERO, e, b, fixed_now()).unwrap_err();
        assert!(matches!(err, InvoiceError::InvalidAmount));
    }

    #[test]
    fn try_new_accepts_minimum_expiry() {
        let (h, w, a, _, b) = ok_args();
        assert!(NewInvoice::try_new(h, w, a, BTC_INVOICE_MIN_SECONDS, b, fixed_now()).is_ok());
    }

    #[test]
    fn try_new_accepts_maximum_expiry() {
        let (h, w, a, _, b) = ok_args();
        assert!(NewInvoice::try_new(h, w, a, BTC_INVOICE_MAX_SECONDS, b, fixed_now()).is_ok());
    }

    #[test]
    fn try_from_events_reconstructs_pending_invoice() {
        let (h, w, a, e, b) = ok_args();
        let now = fixed_now();
        let new = NewInvoice::try_new(h, w, a, e, b, now).unwrap();
        let id = new.id;
        let entity_events = new.into_events();
        let invoice = Invoice::try_from_events(entity_events).expect("hydrate");
        assert_eq!(invoice.id, id);
        assert_eq!(invoice.state, InvoiceState::Pending);
        assert_eq!(invoice.amount_msat, MilliSatoshi::new(1_000_000));
        assert_eq!(invoice.created_at, now);
    }

    #[test]
    fn try_from_events_with_no_events_returns_not_found() {
        let id = InvoiceId::new();
        let empty: EntityEvents<InvoiceEvent> = EntityEvents::init(id, std::iter::empty());
        let err = Invoice::try_from_events(empty).unwrap_err();
        assert!(matches!(err, EsEntityError::NotFound));
    }
}
