//! Strongly-typed entity IDs (UUID v7) generated by the es-entity
//! `entity_id!` macro. Each generated newtype derives `sqlx::Type`,
//! `serde::{Serialize,Deserialize}` (transparent), `Display`, `FromStr`,
//! and `From<Uuid> / From<EntityId> for Uuid`.
//!
//! Only the IDs needed for Slice 1a land here. `PaymentId` (Slice 2,
//! Story 2.1), `HtlcId` (Slice 4, Story 3.1), etc. land alongside the
//! aggregates that own them.

use es_entity::entity_id;

entity_id! {
    InvoiceId,
    WalletId,
    AccountId,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn invoice_id_round_trips_through_string() {
        let id = InvoiceId::new();
        let s = id.to_string();
        let back = InvoiceId::from_str(&s).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn wallet_id_round_trips_through_serde() {
        let id = WalletId::new();
        let json = serde_json::to_string(&id).unwrap();
        let back: WalletId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn ids_have_distinct_types() {
        // Compile-time check: WalletId and AccountId are not interchangeable.
        let w = WalletId::new();
        let a = AccountId::new();
        // No `assert_eq!(w, a)` because the compiler would reject it (different types) —
        // demonstrating the type-safety we want.
        assert_ne!(uuid::Uuid::from(w), uuid::Uuid::from(a));
    }
}
