//! Strongly-typed entity IDs.
//!
//! `InvoiceId` / `PaymentId` are aggregates this gateway owns and
//! event-sources — generated by es-entity's `entity_id!` macro, which
//! gives each a `sqlx::Type` (transparent) + transparent serde +
//! `Display` + `FromStr` + `From<Uuid>` surface, plus a `::new()`
//! UUID-v7 minter. The minter is correct for owned aggregates: this
//! gateway is the authority that creates those ids.
//!
//! `WalletId` is a *foreign reference* owned by blink-core.

use std::fmt;
use std::str::FromStr;

use es_entity::entity_id;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

entity_id! {
    InvoiceId,
    PaymentId,
}

/// Foreign reference to a blink-core wallet. UUID-valued; validated on
/// inbound, never minted here — see the module docs for why there is no
/// `WalletId::new()`.
///
/// Trait surface is deliberately narrower than what `entity_id!` would
/// generate: only what the gateway actually uses today. `Ord` / `Hash`
/// / `From<WalletId> for Uuid` were dropped because nothing reads them;
/// add them back when a real caller appears.
#[derive(sqlx::Type, Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
#[sqlx(transparent)]
pub struct WalletId(Uuid);

impl fmt::Display for WalletId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromStr for WalletId {
    type Err = uuid::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self(Uuid::parse_str(s)?))
    }
}

impl From<Uuid> for WalletId {
    fn from(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn invoice_id_round_trips_through_string() {
        let id = InvoiceId::new();
        let s = id.to_string();
        let back = InvoiceId::from_str(&s).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn wallet_id_round_trips_through_serde() {
        let id = WalletId::from(Uuid::now_v7());
        let json = serde_json::to_string(&id).unwrap();
        let back: WalletId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn wallet_id_from_str_rejects_non_uuid() {
        assert!(WalletId::from_str("not-a-uuid").is_err());
    }

    #[test]
    fn wallet_id_from_str_round_trips() {
        let id = WalletId::from(Uuid::now_v7());
        assert_eq!(WalletId::from_str(&id.to_string()).unwrap(), id);
    }
}
